# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160729_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(null=True, to='app.Food'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(null=True, to='app.Order'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='restaurants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Restaurant'),
        ),
    ]
